include: package:lint/analysis_options.yaml

analyzer:
  enable-experiment:
    - non-nullable
  errors:
    missing_required_param: error
    must_be_immutable: error
    missing_return: error
    sort_unnamed_constructors_first: ignore
    argument_type_not_assignable: ignore
